plugins {
    id "java"
    id 'checkstyle'
    id 'application'
    id 'io.freefair.lombok' version '8.10'
}


group = 'com.epam.aidial'
version = "0.3.0-rc"

apply plugin: 'java'
apply plugin: 'checkstyle'
apply plugin: 'application'
apply plugin: 'io.freefair.lombok'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

checkstyle {
    toolVersion = "10.26.1"
    configDirectory = file("$rootProject.projectDir/checkstyle")
    configProperties = [
            "org.checkstyle.google.suppressionfilter.config":
                    "$rootProject.projectDir/checkstyle/checkstyle-suppressions.xml",
    ]
}

configurations.checkstyle {
    // Security fix:
    resolutionStrategy.force 'org.apache.commons:commons-lang3:3.18.0' // CVE-2025-48924
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.kubernetes:client-java:25.0.0'
    implementation 'commons-io:commons-io:2.16.1'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.5.5'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.5.5'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.5.5'
    testImplementation 'io.projectreactor:reactor-test:3.6.10'
    testImplementation 'org.assertj:assertj-core:3.26.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Security fix:
    implementation 'io.projectreactor.netty:reactor-netty-http:1.2.10' // CVE-2025-22227
    implementation 'org.apache.commons:commons-lang3:3.18.0' // CVE-2025-48924
    implementation 'org.springframework:spring-core:6.2.11' // CVE-2025-41249
}

application {
    mainClass = 'com.epam.aidial.Application'
}

test {
    useJUnitPlatform()
}