name: Release Workflow

on:
  push:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/java_release.yml@1e108657f4040b8bde2ef4e0730d21c468e6d789
    secrets: inherit
    with:
      java_version: 21
